# Generated by Django 4.2 on 2025-07-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_user_email_verification_token_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Не обязательно. 150 символов или меньше.', max_length=150, null=True, verbose_name='username'),
        ),
    ]
